# default is install; make all compiles wrappers,
# but doesn't copy them to $NEXTSIMDIR/python/lib
install:
	@cd bamg/src; make install;

all:
	cd bamg/src; make

clean:
	@cd bamg/src; make clean;

vclean:
	@cd bamg/src; make vclean;
